#!/usr/bin/env bash
# Build the release artifacts and the checksums that authorise running them.
#
# Usage: scripts/release.sh 0.1.0
#
# Writes dist/ and rewrites plugin/checksums.txt. The checksums file is what the
# installer checks a download against, so producing it here -- from the bytes just
# built -- is the only point at which the two are known to agree. Publishing a
# release without rerunning this leaves the installer refusing the new asset, which
# is the correct failure: it will not run what it cannot verify.
set -euo pipefail

version="${1:?usage: scripts/release.sh <version>}"
cd "$(dirname "$0")/.."
rm -rf dist && mkdir -p dist

# Stripped, because -s -w removes a symbol table and DWARF that nothing here reads
# and that cost a third of the binary: 16.3 MB becomes 10.9 MB, and every one of
# these crosses somebody's network.
flags="-s -w -X main.version=${version}"

targets="darwin:arm64 darwin:amd64 linux:amd64 linux:arm64 windows:amd64"
for t in $targets; do
  os="${t%%:*}"; arch="${t##*:}"
  out="dist/cogmer_${version}_${os}_${arch}"
  [ "$os" = windows ] && out="${out}.exe"
  CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" go build -ldflags "$flags" -o "$out" ./cmd/cogmer
  printf '%-44s %s\n' "$(basename "$out")" "$(du -h "$out" | cut -f1)"
done

{
  echo "# sha256 of each released binary, one per line: <sha256>  <asset>"
  echo "#"
  echo "# This file is the ONLY thing that authorises running a downloaded binary."
  echo "# A download whose hash is not listed here is deleted, not run."
  echo "#"
  echo "# Generated by scripts/release.sh for v${version}. Do not edit by hand: a"
  echo "# hash typed rather than computed authorises something nobody has seen."
  echo "#"
  for f in dist/*; do
    if command -v shasum > /dev/null 2>&1; then
      shasum -a 256 "$f" | awk -v n="$(basename "$f")" '{print $1 "  " n}'
    else
      sha256sum "$f" | awk -v n="$(basename "$f")" '{print $1 "  " n}'
    fi
  done
} > plugin/checksums.txt

echo "$version" > plugin/VERSION
echo
echo "wrote plugin/checksums.txt and plugin/VERSION for v${version}"
echo "commit both, then publish dist/* as release v${version}"
